//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountSync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class passwd
    {
        public string user { get; set; }
        public string password { get; set; }
        public bool enabled { get; set; }
        public string Dept { get; set; }
        public string mail_address { get; set; }
        public string fullname { get; set; }
        public string comment { get; set; }
    }
}
