//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountSync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxHmResourceAll
    {
        public decimal deSerialNo { get; set; }
        public string UniversalID { get; set; }
        public string LastModified { get; set; }
        public string FORM { get; set; }
        public string fd_DutyNo { get; set; }
        public string fd_DutyType { get; set; }
        public string fd_OrgDeptFullName { get; set; }
        public string fd_OrgDeptNo { get; set; }
        public string fd_OrgMissionName { get; set; }
        public string fd_OrgMissionUniNo { get; set; }
        public string fd_OrgAffiliateName { get; set; }
        public string fd_OrgAffiliateUniNo { get; set; }
        public string fd_OrgDeptName1 { get; set; }
        public string fd_OrgDeptName2 { get; set; }
        public string fd_OrgDeptName3 { get; set; }
        public string fd_OrgDeptName4 { get; set; }
        public string fd_OrgDeptName5 { get; set; }
        public string fd_OrgDeptNo1 { get; set; }
        public string fd_OrgDeptNo2 { get; set; }
        public string fd_OrgDeptNo3 { get; set; }
        public string fd_OrgDeptNo4 { get; set; }
        public string fd_OrgDeptNo5 { get; set; }
        public string fd_OrgDeptCmpNo { get; set; }
        public string fd_OrgLevel { get; set; }
        public string fd_OrgDutyName { get; set; }
        public string fd_OrgDutyClass { get; set; }
        public string fd_OrgTitleName { get; set; }
        public string fd_OrgByWork { get; set; }
        public string fd_WrkDeptFullName { get; set; }
        public string fd_WrkDeptNo { get; set; }
        public string fd_WrkMissionName { get; set; }
        public string fd_WrkMissionUniNo { get; set; }
        public string fd_WrkAffiliateName { get; set; }
        public string fd_WrkAffiliateUniNo { get; set; }
        public string fd_WrkDeptName1 { get; set; }
        public string fd_WrkDeptName2 { get; set; }
        public string fd_WrkDeptName3 { get; set; }
        public string fd_WrkDeptName4 { get; set; }
        public string fd_WrkDeptName5 { get; set; }
        public string fd_WrkDeptNo1 { get; set; }
        public string fd_WrkDeptNo2 { get; set; }
        public string fd_WrkDeptNo3 { get; set; }
        public string fd_WrkDeptNo4 { get; set; }
        public string fd_WrkDeptNo5 { get; set; }
        public string fd_WrkDeptCmpNo { get; set; }
        public string fd_WrkDutyName { get; set; }
        public string fd_WrkDutyClass { get; set; }
        public string fd_WrkByWork { get; set; }
        public string fd_ChnName { get; set; }
        public string fd_EngName { get; set; }
        public string fd_ID { get; set; }
        public string fd_EleSign { get; set; }
        public string fd_EmpNo { get; set; }
        public string fd_EmpTitleName { get; set; }
        public string fd_ArrDate { get; set; }
        public string fd_SArrDate { get; set; }
        public string fd_QuitDate { get; set; }
        public string fd_WorkSDate { get; set; }
        public string fd_WorkEDate { get; set; }
        public string fd_WrkStatus { get; set; }
        public string fd_MngClass { get; set; }
    }
}
