//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountSync.Models.DB_GEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenProxyAccount
    {
        public string chUserID { get; set; }
        public string chXData { get; set; }
        public string chUserName { get; set; }
        public string chDeptName { get; set; }
        public string chEMail { get; set; }
        public string chEndDate { get; set; }
        public Nullable<System.DateTime> dtEndDate { get; set; }
        public Nullable<System.DateTime> dtLastModified { get; set; }
        public string chXDataHosp { get; set; }
        public string chUserType { get; set; }
        public string chUserID10 { get; set; }
    }
}
