//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountSync.Models.HISAccount
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenUserProfile1
    {
        public string chUserID { get; set; }
        public string chUserPass { get; set; }
        public string chUserName { get; set; }
        public string chStartDate { get; set; }
        public string chEndDate { get; set; }
        public string chXData { get; set; }
        public string chRandomKey { get; set; }
        public string chLastModifyID { get; set; }
        public Nullable<System.DateTime> sdLastModifyDate { get; set; }
    }
}
